all:
  hosts:
    192.168.31.5:
      ansible_user: pi
      ansible_python_interpreter: auto
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_python_interpreter: /usr/bin/python3
